apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests: 
          memory: 1Gi
          cpu:  .5 
        limits:
          memory: 2Gi
          cpu:   1