apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx

  affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: app
             operator: In
             values:
             - frontend
             - backend