apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
  initContainers:
    - name: busybox
      image: buxybox
      command: ["sleep","20"]